### ISSUE TITLE
Add support for block commands

### ISSUE THREAD

**Issue by SynergyBest** [jamespeapen/swayconfig.vim#1]
According to the sway man page you can use commands in block form by using the command in the form `command { <subcommands...> }` see https://github.com/swaywm/sway/blob/master/sway/sway.5.scd#description

However, when you use this form, the syntax is marked red.
![image](https://user-images.githubusercontent.com/72149158/147395891-5e6b86ac-a147-463f-bd42-d8f9f607324c.png)
Would it be possible for you to implement this feature?

**Comment by SynergyBest** [comment]
Oddly enough the block code is no longer being highlighted red, but could it be implemented so that the command is highlighted? 
![image](https://user-images.githubusercontent.com/72149158/147396075-dbfe87d7-dbc6-4107-93fe-abd2e05488f0.png)

**Comment by SynergyBest** [comment]
Awesome, thanks!

**Comment by SynergyBest** [comment]
Will these changes be merged into i3config by chance?

**Comment by jamespeapen** [comment]
I haven't seen much activity on that repo in the last few months, so I wasn't planning on a PR.
