### ISSUE TITLE
Output blocks are parsed as errors

### ISSUE THREAD

**Issue by 4e554c4c** [jamespeapen/swayconfig.vim#11]
see neovim/neovim#20436

**Comment by jamespeapen** [comment]
Thanks for the report. This is fixed in this repo (https://github.com/jamespeapen/swayconfig.vim/commit/00705ec60c4c04fac24294ed7a260a09fc32ef9f) if you use it as a plugin. However, the fix for it is still a pull request on the vim repo (https://github.com/vim/vim/pull/10600).

**Comment by 4e554c4c** [comment]
oh awesome, I'll just use this repo.
