### ISSUE TITLE
Add support for xwayland command

### ISSUE THREAD

**Issue by SynergyBest** [jamespeapen/swayconfig.vim#2]
Sorry! I forgot to mention this in the old issue, honestly I'm not too familiar with vim syntax files otherwise I would submit a pr.
The commands are `xwayland enable` , `xwayland disable` and `xwayland force`

**Comment by jamespeapen** [comment]
I haven't used those commands in my config. Could you post an example?

**Comment by SynergyBest** [comment]
You can find more info about it [on the sway wiki](https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland), [the xwayland website](https://wayland.freedesktop.org/xserver.html), and [on the sway manpage under commands](https://github.com/swaywm/sway/blob/master/sway/sway.5.scd#commands)

**Comment by jamespeapen** [comment]
Implemented in 4c959b7.

**Comment by SynergyBest** [comment]
Sorry for the late response, I can confirm that it works!
