### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by qubidt** [jamespeapen/swayconfig.vim#4]
Documenting some missing keywords (links to man page):

* [`client.focused_tab_title`](https://github.com/swaywm/sway/blame/cab2189aa64d04ba79dc2cbf19400435b47cdbd2/sway/sway.5.scd#L564-L568)
* [`bindgesture`](https://github.com/swaywm/sway/blame/cab2189aa64d04ba79dc2cbf19400435b47cdbd2/sway/sway.5.scd#L491-L496) (on master but not yet in latest release: 1.7)

**Comment by jamespeapen** [comment]
Thanks! I'll add those.

**Comment by qubidt** [comment]
Thanks! And this is not directly related, but it's the reason I noticed the missing definitions while I was digging through the syntax definitions in the first place. 

```
exec swayidle -w -d \
        lock "echo" \
        before-sleep "echo"
```

e.g.: 
![image](https://user-images.githubusercontent.com/6306455/174821982-ca574eb3-4b7b-4e02-a08a-c428a9050805.png)


I can't see anything obvious. And it's only this specific set of line-continuations. If I change up the order or add parameters it goes away. Is there anything obvious I'm not seeing?

**Comment by jamespeapen** [comment]
I've noticed the same thing and I'm not sure why that is. It seems like there's something about the number of lines before the sleep line - an odd number of lines shows an error.
![ss](https://user-images.githubusercontent.com/39574560/174827120-b41c6d65-f3c6-482e-b5f0-4fd3f9982c2f.png)
![ss](https://user-images.githubusercontent.com/39574560/174827231-09265068-0917-4336-873e-ab18df499de5.png)
![ss](https://user-images.githubusercontent.com/39574560/174827393-4893d141-6134-4440-bc77-f9a8571665d5.png)

**Comment by jamespeapen** [comment]
@qubidt I'm working on the `bindgesture` syntax and I don't fully understand how the `hold` command can be used. Can you provide examples of some use cases?

As I understand (and have set up) `bindgesture hold:2 [command]` works, but `hold:2:[any direction]` is invalid.

**Comment by qubidt** [comment]
That's how I'm interpreting it as well. Unfortunately I don't have an up to date sway built ATM to test. Looking at the code tho:

The parser doesn't differentiate between the gesture type, so I don't expect an actual config parsing error.

https://github.com/swaywm/sway/blob/cab2189aa64d04ba79dc2cbf19400435b47cdbd2/common/gesture.c#L47-L103

But the direction never gets set for hold gestures 

https://github.com/swaywm/sway/blob/cab2189aa64d04ba79dc2cbf19400435b47cdbd2/common/gesture.c#L317-L335

So my assumption is that `hold:2:[direction]` would be silently treated equivalently to `hold:2`. I think you're doing the right thing
