### ISSUE TITLE
Newline errors

### ISSUE THREAD

**Issue by jamespeapen** [jamespeapen/swayconfig.vim#5]
It seems like there's something about the number of lines before the sleep line - an odd number of lines shows an error.
![ss](https://user-images.githubusercontent.com/39574560/174827120-b41c6d65-f3c6-482e-b5f0-4fd3f9982c2f.png)
![ss](https://user-images.githubusercontent.com/39574560/174827231-09265068-0917-4336-873e-ab18df499de5.png)
![ss](https://user-images.githubusercontent.com/39574560/174827393-4893d141-6134-4440-bc77-f9a8571665d5.png)

**Comment by jamespeapen** [comment]
@qubidt does this fix the error for you?

**Comment by wundrweapon** [comment]
I'm experiencing the same issue on latest commit. I suspect vim's default swayconfig implementation is being loaded and ignoring yours. Even if I add a `syn clear` at the top of the file, even if I remove the `fini` statement, even if I move the file to `~/.vim/syntax/swayconfig.vim`, even if I do all three. Similarly, `floating_modifier` gets highlighted like a syntax error.

**Comment by jamespeapen** [comment]
@wundrweapon What version of vim are you using? The sway-specific syntax just got added to upstream vim

**Comment by wundrweapon** [comment]
Looks like v9.0.0135, which the `version` variable reports as 900

**Comment by jamespeapen** [comment]
And does vim recognize the file as swayconfig? What does it look like if you unload this plugin?

**Comment by wundrweapon** [comment]
Vim does recognize swayconfig. Before installing this, `echo &ft` would report "swayconfig". The issues I mentioned before (line continuations and `floating_modifier` happen by default, which is why I suspected vim isn't loading your syntax. How and why, I do not know
