### ISSUE TITLE
One line input commands are highlighted as incorrect

### ISSUE THREAD

**Issue by timeopochin** [jamespeapen/swayconfig.vim#6]
Each of these lines are highlighted as incorrect, but they function perfectly with sway

    input * xkb_layout fr(bepo)
    input 1386:20762:Wacom_HID_511A_Finger map_to_output eDP-1
    input 1386:20762:Wacom_HID_511A_Pen map_to_output eDP-1

They are however highlighted as normal text when braces and newlines are added, for example:

    input * {
      xkb_layout fr(bepo)
    }

This is not an issue with `output`:

    output * bg $HOME/.config/sway/bg.png fill

Though the `output` looses it’s colour when adding the braces

**Comment by jamespeapen** [comment]
Fixed the input highlighting in 193c2e9 and output losing its color in 5369682.
